### ISSUE TITLE
Improve Scrambler Efficiency

### ISSUE THREAD

**Issue by russellbaxt** [russellbaxt/CubeTimer#2]
Improve the efficiency of the scrambler as well as format and debug it.

**Comment by kianhighland** [comment]
you might want to start over on this becouse I made some Improvements on the code and I don't know how we could get both improvements

**Comment by russellbaxt** [comment]
It doesn't really matter because I had made a new method.

**Comment by kianhighland** [comment]
Are you going to come to my house?
Should I bike you yours first or do you want to just use your phone to get to mine?

**Comment by russellbaxt** [comment]
I'm biking over in about five minutes.

On Tuesday, June 16, 2015, kianhighland notifications@github.com wrote:

> Are you going to come to my house?
> Should I bike you yours first or do you want to just use your phone to get
> to mine?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/russellbaxt/CubeTimer/issues/2#issuecomment-112494887
> .

## 

Russ

**Comment by russellbaxt** [comment]
I looked at google maps so I know how to get there.

On Tuesday, June 16, 2015, kianhighland notifications@github.com wrote:

> Are you going to come to my house?
> Should I bike you yours first or do you want to just use your phone to get
> to mine?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/russellbaxt/CubeTimer/issues/2#issuecomment-112494887
> .

## 

Russ
